---
- hosts: wp-ftw
  gather_facts: false
  vars_files:
    - vars/private.yml
    - vars/all.yml
  tasks:
    # connection test
    # - name: ls
    #   shell: ls
    #   register: stdio
    #   changed_when: no
    # - name: show
    #   debug:
    #     msg: "{{ stdio }}"

    - name: deploy .bash_profile
      tags:
       - never
       - init
       - bash
      ansible.builtin.include_tasks:
        roles/bash/tasks/main.yml

    - name: deploy .zshrc
      tags:
       - never
       - init
       - zsh
      ansible.builtin.import_tasks:
        roles/zsh/tasks/main.yml